Revert "set armhf arch for wandboard-solo"
This reverts commit d5cbd1c76484ca74a63c6cee1453b9b7005a266c.
cause errors:

W: Unable to read /home/vagrant/build/tmp/work/wandboard_solo
 -poky-linux-gnueabi/core-image-xbt/1.0-r0/apt/preferences.d/
 - DirectoryExists (2: No such file or directory)
E: Unable to locate package locale-base-en-us
E: Unable to locate package locale-base-en-gb

ERROR: Function failed: do_rootfs